//! Unlock routines: shared logic (`logic.rs`), HTTP handler (`http.rs`), and MCP tool (`mcp.rs`,
//! declared from `routes::mcp` so it can reach `MoadimMcp`'s private state).

pub(crate) mod logic;

#[path = "http.rs"]
mod http;
#[allow(
    unused_imports,
    reason = "utoipa's OpenApi derive resolves this hidden __path_unlock_routines type via crate::routes::unlock_routines::__path_unlock_routines, generated by #[utoipa::path] on the re-exported handler below"
)]
pub use http::{__path_unlock_routines, unlock_routines};
