//! Get routine: shared logic (`logic.rs`), HTTP handler (`http.rs`), and MCP tool (`mcp.rs`,
//! declared from `routes::mcp` so it can reach `MoadimMcp`'s private state).

pub(crate) mod logic;

#[path = "http.rs"]
mod http;
#[allow(
    unused_imports,
    reason = "utoipa's OpenApi derive resolves this hidden __path_get_routine type via crate::routes::get_routine::__path_get_routine, generated by #[utoipa::path] on the re-exported handler below"
)]
pub use http::{__path_get_routine, get_routine};
