//! Lock routines: shared logic (`logic.rs`), HTTP handler (`http.rs`), and MCP tool (`mcp.rs`,
//! declared from `routes::mcp` so it can reach `MoadimMcp`'s private state).

pub(crate) mod logic;
pub use logic::LockRequest;

#[path = "http.rs"]
mod http;
#[allow(
    unused_imports,
    reason = "utoipa's OpenApi derive resolves this hidden __path_lock_routines type via crate::routes::lock_routines::__path_lock_routines, generated by #[utoipa::path] on the re-exported handler below"
)]
pub use http::{__path_lock_routines, lock_routines};
