import { test, expect } from "@playwright/test";
import { installApiMocks } from "./moadimApiMocks";

test("multiple machines persist in last view, saved views and share links", async ({ page, browser }, testInfo) => {
  await installApiMocks(page);
  await page.goto("/routines");
  const summary = page.getByLabel("Machine filter", { exact: true });
  await summary.click();
  await page.getByRole("checkbox", { name: "m1", exact: true }).check();
  await expect(page.getByText("Showing 2 of 3")).toBeVisible();
  await page.getByRole("checkbox", { name: "mini-lab", exact: true }).check();
  await expect(page.getByText("Showing 3 of 3")).toBeVisible();
  await expect(summary).toHaveText("2 selected");
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("multi-machine.png"), fullPage: true });
  await page.locator(".machine-filter-options").screenshot({ path: testInfo.outputPath("multi-machine-control.png") });
  await summary.click();
  await page.getByRole("button", { name: "☆ SAVE VIEW", exact: true }).click();
  await page.getByLabel("New view name").fill("Two machines");
  await page.getByRole("button", { name: "SAVE", exact: true }).click();
  await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.getByRole("button", { name: "🔗 COPY LINK", exact: true }).click();
  const shared = await page.evaluate(() => navigator.clipboard.readText());
  expect(new URL(shared).searchParams.getAll("machine")).toEqual(["m1", "mini-lab"]);
  await page.reload();
  await expect(summary).toHaveText("2 selected");
  await page.goto("/routines");
  await expect(summary).toHaveText("2 selected");
  await summary.click();
  await page.getByRole("checkbox", { name: "m1", exact: true }).uncheck();
  await expect(page.getByText("Showing 2 of 3")).toBeVisible();
  await page.getByRole("button", { name: "Any machine", exact: true }).click();
  await expect(summary).toHaveText("Any");
  await summary.click();
  await page.getByLabel("Saved views").selectOption("");
  await page.getByLabel("Saved views").selectOption("Two machines");
  await expect(summary).toHaveText("2 selected");
  const context = await browser.newContext();
  const recipient = await context.newPage();
  await installApiMocks(recipient);
  await recipient.goto(shared);
  await expect(recipient.getByLabel("Machine filter", { exact: true })).toHaveText("2 selected");
  await context.close();
  await page.getByRole("button", { name: "CLEAR", exact: true }).click();
  await expect(summary).toHaveText("Any");
  expect(new URL(page.url()).searchParams.has("machine")).toBe(false);
});


test("legacy machine links support keyboard selection, None and other facets", async ({ page }) => {
  await installApiMocks(page);
  await page.goto("/routines?machine=m1");
  const summary = page.getByLabel("Machine filter", { exact: true });
  await expect(summary).toHaveText("m1");
  await expect(page.getByText("Showing 2 of 3")).toBeVisible();
  await summary.focus();
  await page.keyboard.press("Enter");
  const second = page.getByRole("checkbox", { name: "mini-lab", exact: true });
  await second.focus();
  await page.keyboard.press("Space");
  await expect(summary).toHaveText("2 selected");
  await page.getByRole("checkbox", { name: "None (unassigned)", exact: true }).check();
  await expect(summary).toHaveText("3 selected");
  await summary.click();
  await page.getByLabel("Tag filter").selectOption("digest");
  await expect(page.getByText("Showing 1 of 3")).toBeVisible();
  await page.getByRole("button", { name: "CLEAR", exact: true }).click();
  await summary.click();
  await second.check();
  await second.uncheck();
  await expect(summary).toHaveText("Any");
  await expect(page.getByText("Showing 3 of 3")).toBeVisible();
  await page.getByRole("checkbox", { name: "None (unassigned)", exact: true }).check();
  await expect(summary).toHaveText("None");
  await expect(page.getByText("Showing 0 of 3")).toBeVisible();
});
