//! List routine runs: shared logic (`logic.rs`), HTTP handler (`http.rs`), and MCP tool
//! (`mcp.rs`, declared from `routes::mcp` so it can reach `MoadimMcp`'s private state).

pub(crate) mod logic;

#[path = "http.rs"]
mod http;
#[allow(
    unused_imports,
    reason = "utoipa's OpenApi derive resolves this hidden __path_list_routine_runs type via crate::routes::list_routine_runs::__path_list_routine_runs, generated by #[utoipa::path] on the re-exported handler below"
)]
pub use http::{__path_list_routine_runs, list_routine_runs};
