//! Create flag: shared logic (`logic.rs`), HTTP handler (`http.rs`), and MCP tool (`mcp.rs`,
//! declared from `routes::mcp` so it can reach `MoadimMcp`'s private state).

pub(crate) mod logic;
pub use logic::CreateFlagRequest;

#[path = "http.rs"]
mod http;
#[allow(
    unused_imports,
    reason = "utoipa's OpenApi derive resolves this hidden __path_create_flag type via crate::routes::create_flag::__path_create_flag, generated by #[utoipa::path] on the re-exported handler below"
)]
pub use http::{__path_create_flag, create_flag};
